version: "3.7"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  chat_bot:
    build: ./chat_bot
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:  bash -c "python ./bin/test_bot.py"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017
#    command: bash -c "while true; do echo hello; sleep 2; done"

volumes:
  mongodb:
