version: "3.7"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  chat_bot:
    build:
      context: ./
      dockerfile: ./chat_bot/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./logs
        target: /home/chat_bot/logs
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017
  # updates expired subscription and ads
  expire_script:
    build:
      context: ./
      dockerfile: ./expire_script/Dockerfile
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./logs
        target: /home/expire_script/logs
    environment:
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017
  # polls yoomoney for new payments
  poll_yoomoney:
    build:
      context: ./
      dockerfile: ./poll_yoomoney/Dockerfile
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./logs
        target: /home/poll_yoomoney/logs
    environment:
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017
  scraper:
    build:
      context: ./
      dockerfile: ./scraper/Dockerfile
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./logs
        target: /home/scraper/logs
    environment:
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017
      - API_ID=9829389
      - API_HASH=638fd04be80e8d64cf3fd68e861b0e12
      - HOURS_TO_SCRAPE=48


Hours_to_scrape = 48
# to run cotainer indefinitely
#    command: bash -c "while true; do echo hello; sleep 2; done"

volumes:
  logs:
  mongodb:
