version: "3.7"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  chat_bot:
    build:
      context: ./
      dockerfile: ./chat_bot/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./logs
        target: /logs
    command:  bash -c "python -u ./bin/test_bot.py"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017
  # updates expired subscription and ads
  expire_script:
    build:
      context: ./
      dockerfile: ./expire_script/Dockerfile
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db
      - PORT=27017

# to run cotainer indefinitely
#    command: bash -c "while true; do echo hello; sleep 2; done"

volumes:
  logs:
  mongodb:
