name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-20.04
    matrix:
      include:
        - dockerfile: ./chat_bot/Dockerfile
          secrets: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
          - if: ${{ matrix.secrets }}
            secrets: ${{ matrix.secrets }}

#  redeploy:
#    name: Redeploy - Webhook call
#    runs-on: ubuntu-20.04
#    needs: [ build ]
#    steps:
#      - name: Deploy docker container webhook
#        uses: joelwmale/webhook-action@master
#        env:
#          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
#          data: "{ 'myField': 'myFieldValue'}"
